name: changelog

on:
  push:
    branches:
      - master

jobs:
  generate:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "✏️ Generate release changelog"
      uses: heinrichreimer/action-github-changelog-generator@v2.3
      with:
        token: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
    - name: Commit CHANGELOG.md
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: master
        commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
        file_pattern: CHANGELOG.md
